# Site settings
title: Douze's landmark
description: Frontend of my GitHub repositories. Graphics programming, and stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://douze.github.io"
github_username:  douze
logo: /assets/icons/logo.svg

# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Data settings
collections:
  projects:
    output: true

# Front Matter Defaults
defaults:
  # projects
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: post
      read_time: true

